# Generated by Django 3.1.7 on 2021-05-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landingform',
            fields=[
                ('landing_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'landingform',
                'managed': False,
            },
        ),
    ]
