# Generated by Django 3.1.7 on 2021-05-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_landingform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='image',
            new_name='imageone',
        ),
        migrations.RemoveField(
            model_name='home',
            name='content',
        ),
        migrations.RemoveField(
            model_name='home',
            name='content_two',
        ),
        migrations.AddField(
            model_name='home',
            name='about_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='home',
            name='about_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='home',
            name='button_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='home',
            name='imagethree',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='home',
            name='imagetwo',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='home',
            name='service_title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='detail_word',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='list_content',
            field=models.TextField(default=''),
        ),
    ]
